### ISSUE TITLE
duplicate connections in connections GQL query

### ISSUE THREAD

**Issue by austinmilt** [holaplex/indexer#501]
The Graph QL `connections` query is returning duplicate entries, e.g. in the query below for everyone following the given address, ArtbyBethC (and the acommpanying wallet address) appears twice.

```
query {
	connections(to: "232PpcrPc6Kz7geafvbRzt5HnHP4kX88yvzUCN69WXQC", limit: 100, offset: 0) {
    from {
      twitterHandle
      address
    }
  } 
}
```

```
{
  "data": {
    "connections": [
      ...
      {
        "from": {
          "twitterHandle": "ArtbyBethC",
          "address": "Dk2qwKdEHGsLNmCsRVsxVRY8eFFGDyZxk8uhUtY3qNT1"
        }
      },
      {
        "from": {
          "twitterHandle": "ArtbyBethC",
          "address": "Dk2qwKdEHGsLNmCsRVsxVRY8eFFGDyZxk8uhUtY3qNT1"
        }
      },
...
}
```

likewise for everyone the address follows

```
query {
	connections(from: "232PpcrPc6Kz7geafvbRzt5HnHP4kX88yvzUCN69WXQC", limit: 100, offset: 0) {
    to {
      twitterHandle
      address
    }
  } 
}
```

```
...
     {
        "to": {
          "twitterHandle": "afkehaya",
          "address": "7r8oBPs3vNqgqEG8gnyPWUPgWuScxXyUxtmoLd1bg17F"
        }
      },
      {
        "to": {
          "twitterHandle": "afkehaya",
          "address": "7r8oBPs3vNqgqEG8gnyPWUPgWuScxXyUxtmoLd1bg17F"
        }
      },
...
```

**Comment by ray-kast** [comment]
I believe this was fixed?

**Comment by austinmilt** [comment]
Sorry, still not fixed. See e.g. entries for `afkehaya` using the query in the original post

**Comment by kristianeboe** [comment]
@dandlezzz for viz

**Comment by kristianeboe** [comment]
This is fixed on the frontend for now, moving it to backlog
